{% set name = "h5io" %}
{% set version = "0.1.1" %}
{% set sha256 = "3412b962a418b38312bcbe2ac41404258bb1adbf6fdaed3b1ca17fcd7f6f5f70" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - numpy
  run:
    - python
    - pip
    - numpy
    - h5py

test:
  imports:
    - h5io
  commands:
    - pip check

about:
  home: http://github.com/h5io/h5io
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'Python Objects Onto HDF5'
  description: |
    h5io is a package designed to facilitate saving some standard Python objects into the 
    forward-compatible HDF5 format. It is a higher-level package than h5py.
  doc_url: https://github.com/h5io/h5io
  dev_url: https://github.com/h5io/h5io

extra:
  recipe-maintainers:
    - larsoner
    - jan-janssen
