{% set name = "h5io" %}
{% set version = "0.1.6" %}
{% set sha256 = "3287e5172a2556d2c54bff743a1a826e6daf368f6eca0f37b7be08a99dec5c14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
  run:
    - python >=3.6
    - pip
    - numpy
    - h5py

test:
  imports:
    - h5io
  commands:
    - pip check

about:
  home: http://github.com/h5io/h5io
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: Python Objects Onto HDF5
  description: |
    h5io is a package designed to facilitate saving some standard Python objects into the 
    forward-compatible HDF5 format. It is a higher-level package than h5py.
  doc_url: https://github.com/h5io/h5io
  dev_url: https://github.com/h5io/h5io

extra:
  recipe-maintainers:
    - larsoner
    - jan-janssen
