travis:
  secure:
    BINSTAR_TOKEN: GAlLjm75jsKVvcJh9YJp2+LbYIjMEfS6Oq1heS4L8uxgq9bqObCenX1jNe4/kJIlQ+sR0AEPBQcPUTLf/YRexIWFZFd1VW1R4/SxrlnOUQwLtNPs4V2E1Sd8qTrGF09JdVXa+LpUamyHL8FxMQHPaPvW5zF91Im+5DlvgbGFph8UGJgL7eM7CbEyU7COlmJS+cN/xFugNbZkEG3ET2FU/TSHBCyBwbr3HRoJtl8dsXAki85f+Okrjc+BY+dCmDRj9COQtC6/pqPBTYrMV7N2XmmUiqiO1Il4zAc2yRR/2RtD1NPzrFOnr/KYdo/vB4nkJ3mYcmaROQqyCi+TsUF80mlQk8Rp9cq6gXYZDZCrEuIVEH1DIRLZbPbSqKBA0Lcdfi75i29BiqQ5mntmKInNQ5DeWKVys8kU6dy6NPTziKyJN/vnXETURA7HOUimw50o/IDsWhWieOuZxkp3Q0qryak1RCbGygAAh8A37ADFPthIMF0I5qNhkO3wWb9CuAT5btSU33XyEkcZqmvFFyRUc72fyjFYqlgujwffUipytSUgIH9256MMXb4kI963Dje5uw7FyppubjJGreCqMMjKnZ5KKorIevmiOWnVPhQHbrMu0hG8Q6Oxh9/MTJMSmPBR2l0eD4PCVCzJtWK9j82mTtkzxihTf6j10xEDuSxtilg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
